#!/usr/bin/env python3
"""
build_load_staging.py — generate scripts/load_staging.sql from the seed JSON.

Reads seed_accounts.json / seed_contacts.json / seed_products.json and emits batched
INSERT statements into the staging_* tables (migrations/001_staging.sql). The staging
rows mirror the RAW seed shape with no transformation — validation happens on the raw
import first, and the transform into live tables lives in migrations/003_promote.sql.

Every row is tagged load_batch='dynamics_2026_06_30' so the staging load is itself
re-runnable / clearable independently of the promotion.

This generator is deterministic and idempotent: same seed in -> byte-identical SQL out,
so the generated file can be committed and diffed.

Usage:  python scripts/build_load_staging.py
        (writes scripts/load_staging.sql next to the seed files' repo root)
"""

from pathlib import Path
import json

# Repo root is the parent of this scripts/ directory.
REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "scripts" / "load_staging.sql"
LOAD_BATCH = "dynamics_2026_06_30"
ROWS_PER_INSERT = 80  # keep each INSERT well under D1's statement/variable limits

# For each staging table: (table name, source JSON file, ordered column list).
# The column order here is the exact order values are emitted below. loaded_at is
# intentionally omitted so its DEFAULT (datetime('now')) fires on insert.
TABLES = {
    "staging_accounts": {
        "file": "seed_accounts.json",
        "cols": ["seed_id", "dynamics_id", "name", "phone", "website", "city",
                 "state", "country", "postal_code", "street1", "street2",
                 "description", "owner", "status", "created_on", "modified_on",
                 "account_type", "parent_account_name", "parent_seed_id",
                 "formal_name", "notes", "load_batch"],
    },
    "staging_contacts": {
        "file": "seed_contacts.json",
        "cols": ["seed_id", "dynamics_id", "full_name", "first_name", "last_name",
                 "email", "company_name_raw", "business_phone", "mobile_phone",
                 "job_title", "owner", "status", "created_on", "modified_on",
                 "matched_account", "matched_account_seed_id", "match_type",
                 "load_batch"],
    },
    "staging_products": {
        "file": "seed_products.json",
        "cols": ["seed_id", "pn", "name", "structure", "status", "category",
                 "price", "parent_seed_id", "load_batch"],
    },
}


def sql_literal(value):
    """Render a Python value as a safe SQLite literal.

    - None            -> NULL
    - int/float       -> bare number (price is REAL; everything else is TEXT)
    - everything else -> single-quoted string with quotes doubled (SQL escaping)
    """
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        # No booleans expected in the seed, but be explicit rather than silently 0/1.
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def emit_table(table_name, cols, rows):
    """Return the SQL text for one staging table: batched multi-row INSERTs."""
    lines = [f"\n-- {table_name}: {len(rows)} rows (load_batch = {LOAD_BATCH})"]
    header = f"INSERT INTO {table_name} ({', '.join(cols)}) VALUES"

    # Build one tuple of literals per source row. `load_batch` is a synthetic column
    # (not in the JSON), so it is injected as the constant batch tag.
    value_tuples = []
    for row in rows:
        literals = []
        for col in cols:
            if col == "load_batch":
                literals.append(sql_literal(LOAD_BATCH))
            else:
                literals.append(sql_literal(row.get(col)))
        value_tuples.append("(" + ", ".join(literals) + ")")

    # Chunk the tuples into batches so no single INSERT gets too large.
    for start in range(0, len(value_tuples), ROWS_PER_INSERT):
        chunk = value_tuples[start:start + ROWS_PER_INSERT]
        lines.append(header + "\n" + ",\n".join(chunk) + ";")

    return "\n".join(lines) + "\n"


def main():
    parts = [
        "-- scripts/load_staging.sql  (GENERATED by scripts/build_load_staging.py — do not edit by hand)",
        f"-- Source: seed_accounts.json (374) + seed_contacts.json (371) + seed_products.json (131)",
        f"-- Every row tagged load_batch = '{LOAD_BATCH}'.",
        "-- Apply AFTER migrations/001_staging.sql:",
        "--   wrangler d1 execute tsi-intel --local  --file=scripts/load_staging.sql",
        "--   wrangler d1 execute tsi-intel --remote --file=scripts/load_staging.sql",
        "-- Re-runnable: clear first with",
        "--   DELETE FROM staging_accounts; DELETE FROM staging_contacts; DELETE FROM staging_products;",
        "",
    ]

    for table_name, spec in TABLES.items():
        rows = json.loads((REPO_ROOT / spec["file"]).read_text(encoding="utf-8"))
        parts.append(emit_table(table_name, spec["cols"], rows))

    OUT_PATH.write_text("\n".join(parts), encoding="utf-8")

    # Small console summary so the run is self-verifying.
    counts = {name: len(json.loads((REPO_ROOT / spec["file"]).read_text(encoding="utf-8")))
              for name, spec in TABLES.items()}
    print(f"wrote {OUT_PATH.relative_to(REPO_ROOT)}")
    for name, n in counts.items():
        print(f"  {name:18} {n} rows")


if __name__ == "__main__":
    main()
